apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valkey
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chfrchko5/devops-hands-on-project-hivebox
    path: kubernetes/valkey/overlays/prod
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: datastores
  syncPolicy:
    automated:
      prune: True
      selfHeal: True
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true