---
apiVersion: v1
kind: Namespace
metadata:
  name: datastores

---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valkey
  namespace: datastores
spec:
  podManagementPolicy: Parallel
  serviceName: valkey
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      initContainers:
        - name: init-config
          image: busybox
          command: ["sh", "/scripts/init-config.sh"]
          volumeMounts:
            - name: config
              mountPath: /etc/valkey
              readOnly: true
            - name: scripts
              mountPath: /scripts
            - name: workdir
              mountPath: /config
            - name: data
              mountPath: /data
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      containers:
        - name: valkey
          image: valkey/valkey:8.0.1
          ports:
            - name: client
              containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
            - name: workdir
              mountPath: /etc/valkey
            - name: scripts
              mountPath: /scripts
          command: ["sh", "-c"]
          args:
            - |
              valkey-server /etc/valkey/valkey.conf
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REPLICAS
              value: "${replicas}"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
        - name: redis-exporter
          image: oliver006/redis_exporter:latest
          securityContext:
            runAsUser: 59000
            runAsGroup: 59000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 9121
              name: metrics
          env:
            - name: REDIS_ADDR
              value: redis://localhost:6379
      volumes:
        - name: config
          configMap:
            name: valkey
        - name: scripts
          configMap:
            name: valkey
            items:
              - key: init-config.sh
                path: init-config.sh
            defaultMode: 0755
        - name: workdir
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi

---
# service to expose valkey
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: datastores
spec:
  selector:
    app: valkey
  ports:
    - name: client
      port: 6379
      targetPort: 6379
    - name: metrics
      port: 9121
      targetPort: 9121
  clusterIP: None

---
# config map for valkey
apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey
  namespace: datastores
data:
  valkey.conf: |
    protected-mode no
    notify-keyspace-events "KEA$"
    port 6379
    appendonly yes
    replica-read-only no
  
  init-config.sh: |
    #!/bin/sh

    cp /etc/valkey/valkey.conf /tmp/valkey.conf
    cp /tmp/valkey.conf /config/valkey.conf

    mkdir -p /data
    chown -R 1000:1000 /data
