name: lint-and-autotag

on:
    push:
        branches:
            - fix/docker-action-workflow
        paths:
            - 'hivebox-app/**'

jobs:
    lint-and-pytest:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: python linter
              uses: chartboost/ruff-action@v1
              with:
                args: check hivebox-app/.

            - name: python setup
              uses: actions/setup-python@v6

            - name: install dependencies
              run:
                pip install -r hivebox-app/requirements.txt

            - name: run pytest
              run: pytest
              
    auto-tag:
        runs-on: ubuntu-latest
        needs: lint-and-pytest

        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            
            - name: auto tag
              uses: mathieudutour/github-tag-action@v6.2
              id: tag_version
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                release_branches: fix/docker-action-workflow

            - name: create github release from tag
              uses: ncipollo/release-action@v1
              with:
                tag: ${{ steps.tag_version.outputs.new_tag }}
                name: Release ${{ steps.tag_version.outputs.new_tag }}
                body: ${{ steps.tag_version.outputs.changelog }}

    docker-image:
        runs-on: ubuntu-latest
        permissions: write-all
        needs: [lint-and-pytest, auto-tag]
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: lint the dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: hivebox-app/Dockerfile

            - name: docker login
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: get repo tag
              id: tag
              run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            
            - name: create and push docker image
              uses: docker/build-push-action@v6
              with:
                push: true
                context: hivebox-app/.
                tags: chfrchko7/hivebox-app:${{ steps.tag.outputs.TAG }}