name: create docker image

on:
    workflow_run:
        workflows: ["auto increment tag for python app"]
        types:
            - completed

jobs:
    docker-image:
        runs-on: ubuntu-latest
        permissions: write-all
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
              with:
                ref: ${{ github.event.workflow_run.head_branch }}

            - name: lint the dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: hivebox-app/Dockerfile
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: docker login
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: get repo tag
              id: tag
              run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            
            - name: create and push docker image
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: ${{ secrets.DOCKER_USERNAME}}/hivebox-app:${{ steps.tag.outputs.TAG }}