name: sonar qube for code

on:
    # push:
    #     branches:
    #         - main
    #     paths:
    #         - 'hivebox-app/**'
    workflow_dispatch:

jobs:
    sonarqube:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: SonarQube Scan
          uses: sonarsource/sonarqube-scan-action@master

        - name: SonarQube Quality Gate check
          id: sonarqube-quality-gate-check
          uses: sonarsource/sonarqube-quality-gate-action@master
          with:
            pollingTimeoutSec: 200

        - name: "Example show SonarQube Quality Gate Status value"
          run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
